name: Build release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
permissions:
  contents: write
  id-token: write
  attestations: write
env:
  APK_NAME: megnat-${{ github.ref_name }}.apk
  AAB_NAME: megnat-${{ github.ref_name }}.aab
jobs:
  build-android:
    runs-on: ubuntu-latest
    environment: Release
    container: reactnativecommunity/react-native-android:v14.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: cd android && ./gradlew assembleRelease
      - run: mv android/app/build/outputs/apk/release/app-release.apk ${{ env.APK_NAME }}
      - run: mv android/app/build/outputs/bundle/release/app-release.aab ${{ env.AAB_NAME }}
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            ${{ env.APK_NAME }}
            ${{ env.AAB_NAME }}
      - uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: |
            ${{ env.APK_NAME }}
            ${{ env.AAB_NAME }}
