name: Build release
on:
  push:
    tags:
permissions:
  contents: write
jobs:
  build-android:
    runs-on: ubuntu-latest
    environment: Release
    container: reactnativecommunity/react-native-android:v14.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: cd android && ./gradlew clean assembleRelease
      - uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: android/app/build/outputs/apk/release/app-release.apk
