name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:22
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - env:
          EXPO_NO_TYPESCRIPT_SETUP: true
        run: npx expo customize tsconfig.json
      - run: git reset --hard # `expo customize` breaks root tsconfig.json.
      - run: npm test
